module.exports = {
  "PREFIX": ",",
  "AUTO_READ_STATUS": true,
  "MODE": "private",
  "OWNER_NUMBER": "94787751901",
  "READ_CMD": true,
  "AUTO_VOICE": true,
  "AUTO_STICKER": false,
  "AUTO_REPLY": false,
  "AUTO_REACT": false,
  "WELCOME": false,
  "DELMSG": "public",
  "MNAME": "❤🩵 𝙎𝙚𝙣𝙪𝙧𝙖 𝙈𝘿 🩵❤",
  "ANTI_BAD": [],
  "ANTI_BOT": [],
  "ANTI_LINK": [],
  "ANTI_CALL": false,
  "ANTI_DELETE": false,
  "ALWAYS_ONLINE": true,
  "MOROCCOBLOCK": true,
  "BTN_MSG": true,
  "OWNER_NAME": "MR.SENURA",
  "NEWS_JID": false,
  "MOVIE_JID": false,
  "ANIME_JID": false,
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "FOOTER": "> ❤🩵 𝙎𝙚𝙣𝙪𝙧𝙖 𝙈𝘿 🩵❤\n> `Developed by Mr. Senura Herath`",
  "OWNER_REACT": false,
  "EMOJI": "🏷",
  "AI_MODE": false,
  "AI": "Boy",
  "BANNED": [],
  "SUDO": [
    "94787751901"
  ],
  "LANG": "EN",
  "isPremium": false,
  "ALLWAYS_ONLINE": false
};